version: "3.9"  # optional since v1.27.0
services:
  frontapp:
    build: 
      context: ./short-url/.
      dockerfile: Dockerfile
      target: production
    ports:
      - "1234:80"
  apiapp:
    build:
      context: ./ShortUrl.Api/.
      dockerfile: Dockerfile
    ports:
      - "7023:80"
    environment:
      SqlServer__ConnectionString: "Server=db;Database=ShortUrl;User Id=sa;Password=Your_password123;"
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"