// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortUrl.Persistence;

#nullable disable

namespace ShortUrl.Persistence.Migrations
{
    [DbContext(typeof(ShortUrlContext))]
    partial class ShortUrlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ShortUrl.Domain.ShortUrlItem", b =>
                {
                    b.Property<string>("Shortcut")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Shortcut");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("ShortUrlItems");
                });
#pragma warning restore 612, 618
        }
    }
}
